### ISSUE TITLE
Add --(no-)merged options

### ISSUE THREAD

**Issue by themilkman** [matt-harvey/git_curate#19]
Hi there!
First of all: Thanks for this useful tool, I really like it and often use it to clean up my branches.

One thing would be a nice addition: a --(no-)merged option. These would limit the branches shown to those corresponding the parameter.
The option also matches the `git branch` parameter names.
What do you think?

Cheers!

**Comment by matt-harvey** [comment]
Hello there! I'm very happy to hear that you find git_curate to be useful.

That's a great suggestion. I like the idea of adding a --(no-)merged option, mirroring the one for `git branch`.

So, how do you feel about contributing a PR?

**Comment by matt-harvey** [comment]
Hey @themilkman , I've now implemented this on `master`. Please see [this commit](https://github.com/matt-harvey/git_curate/commit/a261718541df7d40094931cbf2ceb92706e63fc4).

I should probably add some test coverage for this too. Not sure when I'll get time to do that TBH.

In the meantime feel free to check out the commit and provide any feedback.

**Comment by themilkman** [comment]
HI @matt-harvey,
first of all sorry for not responding, I am a bit busy atm.
Secondly: Thanks! This looks really good. I just installed and tried it. Works really fine here.
I also took a rough look on the commit and it looks like a very clean implementation - and I understand how this could get extended for future features in a PR (I could see a possible benefit in also handling remote branches for example).
I tested it in a repo with and and another without corresponding matches and it worked fine and as expected.

Again: Great, thank you very much!!

**Comment by matt-harvey** [comment]
No worries @themilkman. Thanks for testing out the commit, glad it's working for you.

I've added some minimal test coverage for the new feature, and have released a new version `1.3.0` so this feature is now available by installing the latest release.

Cheers!
