### ISSUE TITLE
Request: Add Ahead and Behind values for default in branch table

### ISSUE THREAD

**Issue by VjeraTurk** [matt-harvey/git_curate#20]
Add **Ahead** and **Behind** values in a branch table
To support one in making the final decision about deleting the branch.

**Comment by matt-harvey** [comment]
@VjeraTurk This information is already shown in the "Status vs upstream" column.

For example, if your local branch is one commit ahead of the remote, it will say `Ahead 1` in that column. If it's up-to-date with the remote, it will say `Up to date`. Etc.

Am I missing something?
