### ISSUE TITLE
fatal: bad revision '+'

### ISSUE THREAD

**Issue by usq** [matt-harvey/git_curate#8]
Getting this error when running `git curate` in a repository. 

I do have two worktrees ( https://git-scm.com/docs/git-worktree ) which might cause this.
E.g. `git branch` outputs:

```
$ git branch

* feature/foo
  feature/bar
  master
+ develop
```

so the second worktree has `develop` checked out (this might be where the `+` is coming from)

**Comment by matt-harvey** [comment]
Thanks @usq, this is a good catch. I will fix this as soon as I get time&mdash;probably by Friday of this week.

**Comment by matt-harvey** [comment]
Fixed by https://github.com/matt-harvey/git_curate/commit/aaadf2cb04ceb8674469acd2a0de1dc57c800f9b.

Upgrade to [v1.0.1](https://github.com/matt-harvey/git_curate/releases/tag/v1.0.1) to pull in the fix.

Cheers!

**Comment by usq** [comment]
Awesome, works, thank you!
